# Get Ubuntu Image
FROM public.ecr.aws/ubuntu/ubuntu:latest

# Instal prerequisites
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y build-essential git
RUN apt-get install -y git
RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

# Clone git-secrets directorya
RUN git clone https://github.com/awslabs/git-secrets.git && \
    cd git-secrets && \
    make install

WORKDIR /app
RUN mkdir ./utils
COPY utils ./utils
RUN echo $(ls)
RUN echo $(ls ./utils -la)
RUN chmod +x ./utils/git-docker-execute.sh

#CMD [ "sh", "-c", "ls /utils -la" ]
RUN cat ./utils/git-docker-execute.sh
# CMD ["./utils/git-docker-execute.sh"]
RUN bash -c "ls -la /; ls -la ./app; pwd; ./utils/git-docker-execute.sh"

