# Get Python Image
FROM public.ecr.aws/bitnami/python:latest

# Instal prerequisites
RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin && \
    curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /app
RUN mkdir ./utils
COPY utils ./utils
RUN echo $(ls)
RUN echo $(ls ./utils -la)
RUN chmod +x ./utils/grype-docker-execute.sh

RUN bash -c "./grype-docker-execute.sh"