# Get NPM Image
FROM public.ecr.aws/docker/library/node:latest

WORKDIR /app
RUN mkdir ./utils
COPY utils ./utils
RUN echo $(ls)
RUN echo $(ls ./utils -la)
RUN chmod +x ./utils/js-docker-execute.sh

RUN bash -c "./utils/js-docker-execute.sh"