# Get Python Image
FROM public.ecr.aws/bitnami/python:latest

# Instal prerequisites
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir bandit nbconvert jupyterlab

WORKDIR /app
RUN mkdir ./utils
COPY utils ./utils
RUN echo $(ls)
RUN echo $(ls ./utils -la)
RUN chmod +x ./utils/py-docker-execute.sh
RUN cd ..
RUN echo $(ls)
RUN cd ..
RUN echo $(ls)

RUN bash -c "./utils/py-docker-execute.sh"