# Get Ubuntu Image
FROM public.ecr.aws/ubuntu/ubuntu:latest

ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install prerequisites
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git-all python3 python3-pip ruby-full && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install -U checkov && gem install cfn-nag
WORKDIR /app
RUN mkdir ./utils
COPY utils ./utils
RUN echo $(ls)
RUN echo $(ls ./utils -la)
RUN chmod +x ./utils/yaml-docker-execute.sh

RUN bash -c "./yaml-docker-execute.sh"